name: Publish project to Maven repository
on:
  push:
    branches: [ "main" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build
      - name: Archive artifacts
        uses: actions/upload-artifact@master
        with:
          name: jar
          path: build/libs/
